name: bitfood_restaurant
description: BitFood — Painel do Restaurante
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_local_notifications: ^17.2.2
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  intl: ^0.18.1

flutter:
  uses-material-design: true
